"""add_scraped_courses

Revision ID: d0c9adb19fec
Revises: 4dc9f9404d2c
Create Date: 2026-04-20 11:10:01.584517
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0c9adb19fec'
down_revision: Union[str, None] = '4dc9f9404d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraped_courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('instructor', sa.Text(), nullable=True),
    sa.Column('platform_display', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('level', sa.Text(), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('price_idr_approx', sa.Integer(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('has_certificate', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('skills_covered', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('career_tracks', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('description_short', sa.Text(), nullable=True),
    sa.Column('topics_covered', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_indonesia_specific', sa.Boolean(), nullable=False),
    sa.Column('is_bahasa_indonesia', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index('idx_courses_skills', 'scraped_courses', ['skills_covered'], unique=False, postgresql_using='gin')
    op.create_index('idx_courses_source', 'scraped_courses', ['source'], unique=False)
    op.create_index('idx_courses_tracks', 'scraped_courses', ['career_tracks'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_courses_tracks', table_name='scraped_courses', postgresql_using='gin')
    op.drop_index('idx_courses_source', table_name='scraped_courses')
    op.drop_index('idx_courses_skills', table_name='scraped_courses', postgresql_using='gin')
    op.drop_table('scraped_courses')
    # ### end Alembic commands ###
